# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Profile Metrics

on:
  schedule:
    # 00:00 UTC == 8:00 BJS
    - cron: '0 0 * * *'
  # 允许随时手动执行
  workflow_dispatch:
  # 每次指定分支推送自动执行
  # push:
  #   branches:
  #     - main

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: profile-metrics/classic.svg
          # Your GitHub token
          # The following scopes are required:
          #  - public_access (default scope)
          #  - repo
          #  - public_repo
          #  - read:project
          # The following additional scopes may be required:
          #  - read:org      (for organization related metrics)
          #  - read:user     (for user related data)
          #  - read:packages (for some packages related data)
          #  - repo          (optional, if you want to include private repositories)
          token: ${{ secrets.GITHUB_TOKEN }}

          # Options
          user: AAABingBing
          template: classic
          base: header, activity, community
          base_indepth: yes
          config_timezone: Asia/Shanghai
          plugin_habits: yes
          plugin_habits_charts_type: classic
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_from: 200
          plugin_habits_languages_limit: 8
          plugin_habits_languages_threshold: 30%
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_traffic: yes
